local TechTree = require("techtree")

local seg_time = TUNING.SEG_TIME
local day_segs = TUNING.DAY_SEGS_DEFAULT
local dusk_segs = TUNING.DUSK_SEGS_DEFAULT
local night_segs = TUNING.NIGHT_SEGS_DEFAULT
local total_day_time = TUNING.TOTAL_DAY_TIME
local day_time = seg_time * day_segs
local dusk_time = seg_time * dusk_segs
local night_time = seg_time * night_segs

--Warne
TUNING.WARNE_HEALTH = 200
TUNING.WARNE_HUNGER = 175
TUNING.WARNE_SANITY = 75

---Death Touch
TUNING.WARNE_RECOVERY = 3

TUNING.LICH_ABSORB_STAFF_USES = 1
TUNING.LICH_ABSORB_STAFF_USE_PER_HP = 100
TUNING.LICH_ERODE_START_TIME = 1
TUNING.LICH_ERODE_OVER_TIME = seg_time

---Phylactery 
TUNING.WARNE_MAXUSES = 20
TUNING.WARNE_HEALTHPENALTY = .25
TUNING.WARNE_ABSORB_SOUL_USES = 1
TUNING.WARNE_SOUL_REGEN = 10
TUNING.WARNE_SOUL_PERIOD = 3
TUNING.WARNE_REVIVE_DELAY = 2.5

--Spellbook
TUNING.WARNE_SPEELBOOK_NUM_SPELLS = 6

---Staff SpellFocus
TUNING.WARNE_MAXCHARGE = 10

---Staff sanity modifier
TUNING.WARNE_STAFFSANITY = .25

---Rot rate
TUNING.PERISH_WARNE_MULT = 7

---Food multiplier
TUNING.WARNE_FOOD_MULT = 0
TUNING.WARNE_FOODSANITY_MULT = .5

---Generic
TUNING.WARNE_SHADOW_ITEM_RESISTANCE = 0
TUNING.WARNE_READING_SANITY_MULT = 2.5

---Minions
TUNING.WARNE_MINION_ABSORPTION = .20

TUNING.GAMEMODE_STARTING_ITEMS.DEFAULT.WARNE = {
	"warnestaff",
	"warne_souljar",
	"warne_spellbook",
}

TUNING.CHARACTER_DETAILS_OVERRIDE.warne_health = "lichhealth"
TUNING.CHARACTER_DETAILS_OVERRIDE.warne_hunger = "lichhunger"

TUNING.WARNE_LICHHEALTH = TUNING.WARNE_HEALTH
TUNING.WARNE_LICHHUNGER = TUNING.WARNE_HUNGER

---Forge and Gorge
TUNING.LAVAARENA_STARTING_HEALTH.WARNE = 200
TUNING.LAVAARENA_SURVIVOR_DIFFICULTY.WARNE = 1
TUNING.GAMEMODE_STARTING_ITEMS.LAVAARENA.WARNE = {"fireballstaff", "lavaarena_armorlight"}
TUNING.GAMEMODE_STARTING_ITEMS.QUAGMIRE.WARNE = {}

---Cherry Forest Reputation
TUNING.WARNE_CHERRYREP_START_HATE = 0.1